
# -------------------------
#     ESCOLHE PROJETO
# -------------------------


# DESATIVADOS

# { 'tit': 'André G. Bottan',     'arq': 'andre-bottan.sublime-project' },
# { 'tit': 'Apache Config',       'arq': 'apache-config.sublime-project' },
# { 'tit': 'Bujinkan Bauru',      'arq': 'bujinkan-bauru.sublime-project' },
# { 'tit': 'Cálculo de Toras',    'arq': 'toras.sublime-project' },
# { 'tit': 'Cartas e Posts',      'arq': 'cartas-posts.sublime-project' },
# { 'tit': 'Casestore',           'arq': 'casestore.sublime-project' },
# { 'tit': 'COF',                 'arq': 'cof.sublime-project' },
# { 'tit': 'Contas',              'arq': 'contas.sublime-project' },
# { 'tit': 'Dashboard',           'arq': 'dashboard.sublime-project' },
# { 'tit': 'DIG',                 'arq': 'dig.sublime-project' },
# { 'tit': 'EAD',                 'arq': 'ead.sublime-project' },
# { 'tit': 'EAD-Site',            'arq': 'ead-site.sublime-project' },
# { 'tit': 'EAD-Aniversario',     'arq': 'ead-aniversario.sublime-project' },
# { 'tit': 'Eficaz',              'arq': 'eficaz.sublime-project' },
# { 'tit': 'Elementos Produções', 'arq': 'elemprod.sublime-project' },
# { 'tit': 'Excursa Já',          'arq': 'excursa.sublime-project' },
# { 'tit': 'Gestale',             'arq': 'gestale.sublime-project' },
# { 'tit': 'Global Compras',      'arq': 'global-compras.sublime-project' },
# { 'tit': 'Guia de Missas',      'arq': 'guia-de-missas.sublime-project' },
# { 'tit': 'Gulp',                'arq': 'gulp.sublime-project' },
# { 'tit': 'Home André',          'arq': 'home-andre.sublime-project' },
# { 'tit': 'Dir Config',          'arq': 'dirconfig.sublime-project' },
# { 'tit': 'Obadias Móveis',      'arq': 'obadias-moveis.sublime-project' },
# { 'tit': 'Oestesom - Tray',     'arq': 'oestesom-tray.sublime-project' },
# { 'tit': 'Oestesom - Sculpin',  'arq': 'oestesom-sculpin.sublime-project' },
# { 'tit': 'Paroquia Duartina',   'arq': 'paroquia.sublime-project' },
# { 'tit': 'Pisces',              'arq': 'pisces.sublime-project' },
# { 'tit': 'Ponto Cruz',          'arq': 'ponto-cruz.sublime-project' },
# { 'tit': 'Pós Graduação',       'arq': 'pos_graduacao.sublime-project' },
# { 'tit': 'Pós Laravel',         'arq': 'pos-php.sublime-project' },
# { 'tit': 'Processa Imagens',    'arq': 'processa-imagens.sublime-project' },
# { 'tit': 'Pytex Utils',         'arq': 'pytex-pytex.sublime-project' },
# { 'tit': 'Santuário',           'arq': 'santuario.sublime-project' },
# { 'tit': 'Script-Fu',           'arq': 'script-fu.sublime-project' },
# { 'tit': 'Seguro Light',        'arq': 'segurolight.sublime-project' },
# { 'tit': 'SEQ',                 'arq': 'seq.sublime-project' },
# { 'tit': 'Site Padrão',         'arq': 'padrao.sublime-project' }
# { 'tit': 'Sormani Imóveis',     'arq': 'sormani.sublime-project' },
# { 'tit': 'ST-3 Linguagens',     'arq': 'st3-syntax.sublime-project' },
# { 'tit': 'SVG e Ícones',        'arq': 'svg-icons.sublime-project' },
# { 'tit': 'Snippets',            'arq': 'snippets.sublime-project' },
# { 'tit': 'Sweet Timeline',      'arq': 'sweetimeline.sublime-project' },
# { 'tit': 'Targetsale',          'arq': 'targetsale.sublime-project' },
# { 'tit': 'Teste Drupal',        'arq': 'teste-drupal.sublime-project' },
# { 'tit': 'Teste',               'arq': 'teste.sublime-project' },
# { 'tit': 'TESTE LOJA',          'arq': 'teste-loja.sublime-project' },
# { 'tit': 'ToDo',                'arq': 'todo.sublime-project' },
# { 'tit': 'TripleA',             'arq': 'TripleA.sublime-project' },
# { 'tit': 'UML',                 'arq': 'uml.sublime-project' },
# { 'tit': 'Wordpress',           'arq': 'wordpress.sublime-project' },


# ATIVADOS

projetos_config = [

  { 'tit': 'EAD-Aniversario',     'arq': 'ead-aniversario.sublime-project' },
  { 'tit': 'Sormani Imóveis',     'arq': 'sormani.sublime-project' },
  { 'tit': 'Script-Fu',           'arq': 'script-fu.sublime-project' },
  { 'tit': 'EAD-Site',            'arq': 'ead-site.sublime-project' },
  { 'tit': 'Elementos Produções', 'arq': 'elemprod.sublime-project' },
  { 'tit': 'Batch Imagens',       'arq': 'batch-img.sublime-project' },
  { 'tit': 'DIG',                 'arq': 'dig.sublime-project' },
  { 'tit': 'Dir Config',          'arq': 'dirconfig.sublime-project' },
  { 'tit': 'Pisces',              'arq': 'pisces.sublime-project' },
  { 'tit': 'Obadias Móveis',      'arq': 'obadias-moveis.sublime-project' },
  { 'tit': 'André G. Bottan',     'arq': 'andre-bottan.sublime-project' },
  { 'tit': 'Apache Config',       'arq': 'apache-config.sublime-project' },
  { 'tit': 'Pytex Utils',         'arq': 'pytex-utils.sublime-project' },
  { 'tit': 'Guia de Missas',      'arq': 'guia-de-missas.sublime-project' },
  { 'tit': 'Gulp',                'arq': 'gulp.sublime-project' },
  { 'tit': 'Site Padrão',         'arq': 'padrao.sublime-project' },
  { 'tit': 'SVG e Ícones',        'arq': 'svg-icons.sublime-project' },
  { 'tit': 'Seguro Light',        'arq': 'segurolight.sublime-project' },
  { 'tit': 'Shell Scripts Home',  'arq': 'home-andre.sublime-project' },
  { 'tit': 'Bujinkan Bauru',      'arq': 'bujinkan-bauru.sublime-project' },
  { 'tit': 'ST-3 Linguagens',     'arq': 'st3-syntax.sublime-project' },
]
